<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Produto;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProdutoSeeder extends Seeder
{
    public function run(): void
    {
        $produtos = [
            [
                'categoria_slug' => 'quarto',
                'nome' => 'Guarda-Roupa Off-White 6 Portas',
                'preco_de' => 1899,
                'preco' => 1599,
                'imagem_url' => 'assets/images/produtos/guarda-roupa-off-white-6-portas.webp',
                'especificacao' => '6 PORTAS | ACABAMENTO OFF-WHITE',
                'descricao' => 'Guarda-roupa amplo com 6 portas em acabamento off-white e detalhes em madeira natural nos puxadores. Espaço interno com cabideiro e prateleiras.',
                'altura_cm' => 210,
                'largura_cm' => 250,
                'profundidade_cm' => 60,
                'selo' => 'Lancamento',
                'estoque' => 5,
            ],
            [
                'categoria_slug' => 'sala',
                'nome' => 'Buffet Amendoa',
                'preco_de' => 1299,
                'preco' => 999,
                'imagem_url' => 'assets/images/produtos/buffet-amendoa.webp',
                'especificacao' => '4 PORTAS | TAMPO LAQUEADO',
                'descricao' => 'Buffet 4 portas com tampo laqueado em tom amêndoa, espaço interno para louças e utensílios.',
                'altura_cm' => 85,
                'largura_cm' => 150,
                'profundidade_cm' => 45,
                'selo' => 'Oferta',
                'estoque' => 4,
            ],
            [
                'categoria_slug' => 'quarto',
                'nome' => 'Guarda-Roupa 4 Portas',
                'preco_de' => null,
                'preco' => 1499,
                'imagem_url' => 'assets/images/produtos/guarda-roupa-classico-4-portas.webp',
                'especificacao' => '4 PORTAS | ACABAMENTO NOGAL',
                'descricao' => 'Guarda-roupa clássico 4 portas em acabamento nogal, com gaveteiro interno e cabideiro duplo.',
                'altura_cm' => 200,
                'largura_cm' => 180,
                'profundidade_cm' => 55,
                'selo' => null,
                'estoque' => 6,
            ],
            [
                'categoria_slug' => 'quarto',
                'nome' => 'Guarda-Roupa Glossy 4 Portas',
                'preco_de' => 1799,
                'preco' => 1499,
                'imagem_url' => 'assets/images/produtos/guarda-roupa-glossy-4-portas.webp',
                'especificacao' => '4 PORTAS | ACABAMENTO GLOSSY',
                'descricao' => 'Guarda-roupa 4 portas com acabamento glossy de alto brilho, visual moderno e fácil limpeza.',
                'altura_cm' => 205,
                'largura_cm' => 180,
                'profundidade_cm' => 58,
                'selo' => 'Oferta',
                'estoque' => 3,
            ],
            [
                'categoria_slug' => 'quarto',
                'nome' => 'Guarda-Roupa 3 Portas com Gavetas',
                'preco_de' => null,
                'preco' => 1299,
                'imagem_url' => 'assets/images/produtos/guarda-roupa-3-portas-2-gavetas.webp',
                'especificacao' => '3 PORTAS | 2 GAVETAS',
                'descricao' => 'Guarda-roupa compacto 3 portas com 2 gavetas externas, ideal para quartos menores.',
                'altura_cm' => 195,
                'largura_cm' => 140,
                'profundidade_cm' => 55,
                'selo' => null,
                'estoque' => 8,
            ],
            [
                'categoria_slug' => 'quarto',
                'nome' => 'Cômoda Rústica 6 Gavetas',
                'preco_de' => 2199,
                'preco' => 1799,
                'imagem_url' => 'assets/images/produtos/comoda.webp',
                'especificacao' => '6 GAVETAS | MADEIRA MACIÇA',
                'descricao' => 'Cômoda em madeira maciça com acabamento rústico, 6 gavetas amplas com corrediças metálicas reforçadas. Ideal para quarto de casal ou hall de entrada.',
                'altura_cm' => 85,
                'largura_cm' => 160,
                'profundidade_cm' => 45,
                'selo' => null,
                'estoque' => 4,
            ],
            [
                'categoria_slug' => 'quarto',
                'nome' => 'Criado-Mudo Amêndoa',
                'preco_de' => null,
                'preco' => 449,
                'imagem_url' => 'assets/images/produtos/criado-mudo.webp',
                'especificacao' => '2 GAVETAS | ACABAMENTO AMÊNDOA',
                'descricao' => 'Criado-mudo compacto em MDF com acabamento amêndoa, 2 gavetas com puxador em alumínio escovado. Combina com toda a linha de quarto Móveis Soares.',
                'altura_cm' => 55,
                'largura_cm' => 45,
                'profundidade_cm' => 40,
                'selo' => 'Lançamento',
                'estoque' => 12,
            ],
            [
                'categoria_slug' => 'sala',
                'nome' => 'Sofá Rosé Curvo 3 Lugares',
                'preco_de' => 3499,
                'preco' => 2899,
                'imagem_url' => 'assets/images/produtos/sofa.webp',
                'especificacao' => '3 LUGARES | VELUDO ROSÉ',
                'descricao' => 'Sofá de design orgânico e curvo, revestido em veludo rosé, estrutura em madeira maciça e pés palito. Peça statement para salas contemporâneas.',
                'altura_cm' => 75,
                'largura_cm' => 210,
                'profundidade_cm' => 95,
                'selo' => 'Oferta',
                'estoque' => 3,
            ],
            [
                'categoria_slug' => 'sala',
                'nome' => 'Rack para TV até 55" Nordic',
                'preco_de' => 1199,
                'preco' => 999,
                'imagem_url' => 'assets/images/produtos/rack-tv.webp',
                'especificacao' => 'ATÉ 55 POL. | NICHOS ABERTOS',
                'descricao' => 'Rack de TV em madeira clara com detalhes em preto fosco, nichos abertos para organizadores e som ambiente. Suporta TVs de até 55 polegadas.',
                'altura_cm' => 45,
                'largura_cm' => 160,
                'profundidade_cm' => 35,
                'selo' => null,
                'estoque' => 7,
            ],
            [
                'categoria_slug' => 'sala',
                'nome' => 'Mesa de Centro Redonda Carvalho',
                'preco_de' => null,
                'preco' => 799,
                'imagem_url' => 'assets/images/produtos/mesa-centro.webp',
                'especificacao' => 'REDONDA | TAMPO EM CARVALHO',
                'descricao' => 'Mesa de centro redonda com tampo em madeira de carvalho e base em metal preto. Design minimalista que se encaixa em qualquer composição de sala.',
                'altura_cm' => 38,
                'largura_cm' => 90,
                'profundidade_cm' => 90,
                'selo' => null,
                'estoque' => 6,
            ],
            [
                'categoria_slug' => 'escritorio',
                'nome' => 'Mesa de Escritório Minimalista Branca',
                'preco_de' => 799,
                'preco' => 649,
                'imagem_url' => 'assets/images/produtos/mesa-escritorio.webp',
                'especificacao' => '120X60CM | MDF BRANCO FOSCO',
                'descricao' => 'Mesa de escritório com linhas retas e acabamento branco fosco, ideal para home office. Estrutura reforçada, suporta até 40kg de carga distribuída.',
                'altura_cm' => 75,
                'largura_cm' => 120,
                'profundidade_cm' => 60,
                'selo' => 'Oferta',
                'estoque' => 9,
            ],
            [
                'categoria_slug' => 'escritorio',
                'nome' => 'Cadeira Giratória Verde Água',
                'preco_de' => null,
                'preco' => 899,
                'imagem_url' => 'assets/images/produtos/cadeira-escritorio.webp',
                'especificacao' => 'GIRATÓRIA | APOIO DE BRAÇO',
                'descricao' => 'Cadeira de escritório giratória com encosto em tela respirável e assento estofado verde água, apoio de braço regulável e base com rodízios silenciosos.',
                'altura_cm' => 110,
                'largura_cm' => 65,
                'profundidade_cm' => 65,
                'selo' => 'Lançamento',
                'estoque' => 5,
            ],
            [
                'categoria_slug' => 'cozinha',
                'nome' => 'Mesa de Jantar 6 Lugares Preta',
                'preco_de' => 2599,
                'preco' => 2199,
                'imagem_url' => 'assets/images/produtos/mesa-jantar.webp',
                'especificacao' => '6 LUGARES | TAMPO PRETO FOSCO',
                'descricao' => 'Conjunto de mesa de jantar para 6 lugares com tampo em MDF preto fosco e pés em madeira maciça. As cadeiras acompanham estofado branco removível.',
                'altura_cm' => 76,
                'largura_cm' => 160,
                'profundidade_cm' => 90,
                'selo' => null,
                'estoque' => 2,
            ],
            [
                'categoria_slug' => 'cozinha',
                'nome' => 'Cadeira de Cozinha Madeira Clara',
                'preco_de' => null,
                'preco' => 279,
                'imagem_url' => 'assets/images/produtos/cadeira-cozinha.webp',
                'especificacao' => 'MADEIRA CLARA | ESTILO MID-CENTURY',
                'descricao' => 'Cadeira avulsa em madeira clara com design mid-century, assento anatômico. Vendida por unidade - ideal para completar ou renovar seu conjunto de mesa.',
                'altura_cm' => 80,
                'largura_cm' => 45,
                'profundidade_cm' => 50,
                'selo' => null,
                'estoque' => 18,
            ],
        ];

        foreach ($produtos as $produto) {
            $categoria = Categoria::where('slug', $produto['categoria_slug'])->first();

            if (! $categoria) {
                continue;
            }

            Produto::updateOrCreate(
                ['slug' => Str::slug($produto['nome'])],
                [
                    'categoria_id' => $categoria->id,
                    'nome' => $produto['nome'],
                    'preco_de' => $produto['preco_de'],
                    'preco' => $produto['preco'],
                    'imagem_url' => $produto['imagem_url'],
                    'especificacao' => $produto['especificacao'],
                    'descricao' => $produto['descricao'],
                    'altura_cm' => $produto['altura_cm'],
                    'largura_cm' => $produto['largura_cm'],
                    'profundidade_cm' => $produto['profundidade_cm'],
                    'selo' => $produto['selo'],
                    'estoque' => $produto['estoque'],
                    'ativo' => true,
                ]
            );
        }
    }
}
